version: '3'
services:
  db:
    build:
      context: ./database
    environment:
      MYSQL_ROOT_PASSWORD: top-secret-password
    ports:
      - "3306:3306"

  server:
    build:
      context: ./server
    ports:
      - "8080:8080"

  client:
    build:
      context: ./client
    ports:
      - "3000:4200"
