version: '3'
services:
  db:
    build:
      context: ./database
    environment:
      MYSQL_ROOT_PASSWORD: top-secret-password
    ports:
      - "3306:3306"

  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/cms_prod
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: top-secret-password

      SPRING_DATASOURCE_TEST_URL: jdbc:mysql://localhost:3306/cms_test
      SPRING_DATASOURCE_TEST_USERNAME: root
      SPRING_DATASOURCE_TEST_PASSWORD: top-secret-password

  client:
    build:
      context: ./client
    ports:
      - "4200:4200"

